### ISSUE TITLE
Solver settings when solver set to "DEFAULT"

### ISSUE THREAD

**Issue by lordleoo** [MATPOWER/most#13]
it is mentioned in MOST manual that if you set `most.solver` to `DEFAULT`,  MOST will try to look for solvers on your computer, and choose one, with a sequence of priority

``` 
if strcmp(alg, 'DEFAULT')
    if have_fcn('gurobi')       %% use Gurobi by default, if available
        alg = 'GUROBI';
    elseif have_fcn('cplex')    %% if not, then CPLEX, if available
        alg = 'CPLEX';
    elseif have_fcn('mosek')    %% if not, then MOSEK, if available
        alg = 'MOSEK';
    elseif isempty(H) || ~any(any(H))   %% if not, and linear objective
        if have_fcn('intlinprog')       %% then Optimization Tbx, if available
            alg = 'OT';
        elseif have_fcn('glpk')         %% if not, and then GLPK, if available
            alg = 'GLPK';
        end
    else
        error('miqps_matpower: no solvers available - requires CPLEX, Gurobi, MOSEK, INTLINPROG or GLPK');
    end
end
```

if you happened to have anyone of those (GUROBI or CPLEX) on your computer, your choice of `DEFAULT` will be changed to one of these solvers the program proceeds to fetch the options of these solvers, from mpopt.
if you hadn't already sat these options, this will throw the error: "field not found".
 
For example, inside `gurobi_options`, at line 94, the program assumes that mpopt.gurobi already exists, and proceeds to check for a field named `opt_fname`
this will throw an error.
 
The fix would be:
inside `miqps_matpower` and `qps_matpower`
if the program chooses anyone of these priority solvers, it should check if mpopt contains settings for this solver. If not, then some default settings must be set.
 
another fix which I implemented on my copy of most.m is this if-statement
```
if (have_fcn('gurobi') || have_fcn('cplex') || have_fcn('mosek') || have_fcn('intlinprog') || have_fcn('glpk')) && ~any(strcmpi(mpopt.most.solver,{'OT'})) && ~any(strcmpi(fieldnames(mpopt),mpopt.most.solver)) %this whole IF statement was added by baraa

%i could easily use isfield instead of strcmpi(fieldnames), but with isfield the name is case-sensitive
warning(['You forgot to set the solver settings: mpopt.',mpopt.most.solver,...
newline,'Proceeding will throw an error. Instead, I will change solver to OT']); %added by baraa
mpopt.most.solver='OT';
end
```

**Comment by lordleoo** [comment]
i used to get this error earlier, but now it's not showing.
i'm deeply sorry about this
let me close it, and i'll get back to it

**Comment by ajaythakur01** [comment]
I am working on Deterministic Unit Commitment, after running this program there are some errors.
this is my program:
close all;
clc;
casefile = 'ex_case3b';
mpc = loadcase(casefile);
xgd = loadxgendata('ex_xgd_uc',mpc);
[iwind,mpc,xgd] = addwind('ex_wind_uc',mpc,xgd);
profiles = getprofiles('ex_wind_profile_d',iwind);
profiles = getprofiles('ex_load_profile',profiles);
nt=size(profiles(1).values,1); %number of periods
mpc_full = mpc; %save for later
xgd_full = xgd; %save for later
STARTUP = 2; SHUTDOWN = 3;
mpc.gencost(:,[STARTUP SHUTDOWN])= 0; %remove startup/shutdown costs
xgd.MinUp(2) = 1; %remove min up-time constraint
xgd.PositiveLoadFollowReserveQuantity(3)= 250; %remove ramp reserve
xgd.PositiveLoadFollowReservePrice(3)= 1e-6; %constraint and costs
xgd.NegativeLoadFollowReservePrice(3)= 1e-6;
mpopt = mpoption('out.all', 0, 'verbose', 2);
mpopt = mpoption(mpopt,'most.dc_model',1); %use DC network model(default)
mdi = loadmd(mpc,nt,xgd,[],[],profiles);
mdo = most(mdi,mpopt);
ms = most_summary(mdo); %print results,depending on 'vebrose'option
mpc.gencost(2,[STARTUP SHUTDOWN])=[200 200];
mpc.gencost(3,[STARTUP SHUTDOWN])=[3000 600];
%equivalent to doing: mpc = mpc_full
mdi = loadmd(mpc,nt,xgd,[],[],profiles);
mdo = most(mdi,mpopt);
xgd.MinUp(2) = 3;
mdi = loadmd(mpc,nt,xgd,[],[],profiles);
mdo = most(mdi,mpopt);
xgd.PositiveLoadFollowReserveQuatity(3)= 100; %restore ramp reserve
xgd.PositiveLoadFollowReservePrice(3)= 10; %constraint and costs
xgd.NegativeLoadFollowReservePrice(3)= 10;
%equivalent to doing:xgd = xgd_full;
mdi = loadmd(mpc,nt,xgd,[],[],profiles);
%mpopt = mpoption(mpopt,'most.storage.cyclic',1);
[iess,mpc,xgd,sd] = addstorage('ex_storage',mpc,xgd);
mdo = most(mdi,mpopt);

Errors are:
Error using miqps_ot (line 347)
miqps_ot: EXITFLAG from price computation stage = -2

Error in miqps_master (line 218)
[x, f, eflag, output, lambda] = ...

Error in opt_model/solve (line 189)
[x, f, eflag, output, lambda] = ...

Error in most (line 2014)
[mdo.QP.x, mdo.QP.f, mdo.QP.exitflag, mdo.QP.output, mdo.QP.lambda ] = ...

Error in TestProgram_MPUC_1 (line 21)
mdo = most(mdi,mpopt);
