### ISSUE TITLE
Dispatchable loads for UC

### ISSUE THREAD

**Issue by standon41** [MATPOWER/most#20]
Hi,
I am trying to figure out the best way to set up dispatchable loads for a DCOPF unit commitment problem. So far I have changed the genotype to DL. But that does not seem to have any effect. Should I use addgen2mpc? I am trying to modify the generators and not add anything new, will this suffice? Any examples on how I can use this function??

**Comment by rdzman** [comment]
If you are simply looking for a way to disable the commitment decision for the dispatchable loads, then just set the `CommitKey` in the `xGenData` to 2. See Table 5-1 in the [MOST User's Manual](https://matpower.org/docs/MOST-manual-1.1.pdf).

If it's something else you are trying to accomplish, you'll have to be more specific about what you are trying to accomplish and what is not working.

**Comment by standon41** [comment]
I am trying to measure loadshed on busses for every period that I have set up. Matpower has a function called 'load2disp' that I am using. Is there anything else I should adjust in the most settings?
Thank you

**Comment by rdzman** [comment]
No you should be able to use `load2disp` to convert the loads in your case file. You'll just have to make sure that your other inputs match this new case file, e.g. the `xGenData` will need to have the same number of entries as the `mpc.gen` in your new case file.
