### ISSUE TITLE
How to make load profile for 39 bus , 10 Generator System.

### ISSUE THREAD

**Issue by ajaythakur01** [MATPOWER/most#22]
Dear Sir,
We are performing deterministic unit commitment for 39 bus system. We are following example as given in MOST manual for 3 bus system. However in ex-Load_profile data no identification index for load bus is given. So how to make load bus index number in the load profile and how we can enter load profile information for different load buses say for a 12 hour period.

**Comment by rdzman** [comment]
I would suggest you make a copy of `ex_load_profile.m` and in your new file, change the value of `'rows'` in [line 23](https://github.com/MATPOWER/most/blob/489918ca9e605bba45bedcbaaab95238234e0596/lib/t/ex_load_profile.m#L23) to a vector of bus indices of the loads you want to change, then change [line 27](https://github.com/MATPOWER/most/blob/489918ca9e605bba45bedcbaaab95238234e0596/lib/t/ex_load_profile.m#L27) to ...
```
loadprofile.values(:, 1, :) = [
```
and supply the data as a matrix, where the rows correspond to the periods (hours) and the columns correspond to the load buses (i.e. corresponding to the buses indexed by `loadprofile.rows`).

**Comment by ajaythakur01** [comment]
Thank you sir for your response
