### ISSUE TITLE
A typo in most.m file for checking MinDown time

### ISSUE THREAD

**Issue by talha965** [MATPOWER/most#29]
Hi,
I was reading through the most. m file and I realized there is a small bug in checking the MinDown time to be >=1 on line 377 in the most.m file as shown below. The IF condition is only checking MinUp time twice.   

if any(mdi.UC.MinUp < 1) && any(mdi.UC.MinUp < 1)
        error('most: UC.MinUp and UC.MinDown must all be >= 1');
    end

**Comment by rdzman** [comment]
Good catch! Thanks for letting me know. The fix will be in shortly.
