### ISSUE TITLE
Minimization of energy production costs in Matpower software

### ISSUE THREAD

**Issue by scodeppppp** [MATPOWER/most#42]
A detailed description of the completed task. Demonstrate how the network topology changes and how an additional unit is added to an arbitrary node. Illustrate all of this on an arbitrary transmission IEEE system embedded in Matpower (case57/case118).

**Comment by scodeppppp** [comment]
Could someone help me with creating code and make me understand the problem?

**Comment by rdzman** [comment]
I think [FAQ #2](https://matpower.org/doc/faq/#homework) applies here.

If you have a specific question about the use of MOST, feel free to ask it in a new issue.
